In [13]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Amit", "Riya", "Rahul", "Sneha", "Karan", "Pooja", "Arjun", "Neha"],
    "Age": [23, 24, 22, 23, 25, 22, 24, 23],
    "Course": ["MCA", "MCA", "MCA", "MCA", "MCA", "MCA", "MCA", "MCA"],
    "City": ["Pune", "Mumbai", "Delhi", "Pune", "Mumbai", "Delhi", "Pune", "Mumbai"],
    "Marks": [85, np.nan, 76, 88, 95, np.nan, 81, 79],
    "Salary": [30000, 35000, np.nan, 28000, 40000, 32000, np.nan, 29000]
}

df = pd.DataFrame(data)
df

#nan = not a number

    Name  Age Course    City  Marks   Salary
0   Amit   23    MCA    Pune   85.0  30000.0
1   Riya   24    MCA  Mumbai    NaN  35000.0
2  Rahul   22    MCA   Delhi   76.0      NaN
3  Sneha   23    MCA    Pune   88.0  28000.0
4  Karan   25    MCA  Mumbai   95.0  40000.0
5  Pooja   22    MCA   Delhi    NaN  32000.0
6  Arjun   24    MCA    Pune   81.0      NaN
7   Neha   23    MCA  Mumbai   79.0  29000.0

In [8]:
df.isnull()

    Name    Age  Course   City  Marks  Salary
0  False  False   False  False  False   False
1  False  False   False  False   True   False
2  False  False   False  False  False    True
3  False  False   False  False  False   False
4  False  False   False  False  False   False
5  False  False   False  False   True   False
6  False  False   False  False  False    True
7  False  False   False  False  False   False

In [9]:
df.isnull().sum()

Name      0
Age       0
Course    0
City      0
Marks     2
Salary    2
dtype: int64

In [10]:
#fill method1 :-- fill with 0 

df["Marks"].fillna(0)

0    85.0
1     0.0
2    76.0
3    88.0
4    95.0
5     0.0
6    81.0
7    79.0
Name: Marks, dtype: float64

In [11]:
df["Marks"] = df["Marks"].fillna(0)

In [12]:
df

    Name  Age Course    City  Marks   Salary
0   Amit   23    MCA    Pune   85.0  30000.0
1   Riya   24    MCA  Mumbai    0.0  35000.0
2  Rahul   22    MCA   Delhi   76.0      NaN
3  Sneha   23    MCA    Pune   88.0  28000.0
4  Karan   25    MCA  Mumbai   95.0  40000.0
5  Pooja   22    MCA   Delhi    0.0  32000.0
6  Arjun   24    MCA    Pune   81.0      NaN
7   Neha   23    MCA  Mumbai   79.0  29000.0

In [15]:
df["Marks"].mean()

np.float64(84.0)

In [16]:
#fill method :-- fill with mean 
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

In [17]:
df

    Name  Age Course    City  Marks   Salary
0   Amit   23    MCA    Pune   85.0  30000.0
1   Riya   24    MCA  Mumbai   84.0  35000.0
2  Rahul   22    MCA   Delhi   76.0      NaN
3  Sneha   23    MCA    Pune   88.0  28000.0
4  Karan   25    MCA  Mumbai   95.0  40000.0
5  Pooja   22    MCA   Delhi   84.0  32000.0
6  Arjun   24    MCA    Pune   81.0      NaN
7   Neha   23    MCA  Mumbai   79.0  29000.0

In [18]:
#fillmethod 3:-- dropna()

In [20]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df

    Name  Age Course    City  Marks        Salary
0   Amit   23    MCA    Pune   85.0  30000.000000
1   Riya   24    MCA  Mumbai   84.0  35000.000000
2  Rahul   22    MCA   Delhi   76.0  32333.333333
3  Sneha   23    MCA    Pune   88.0  28000.000000
4  Karan   25    MCA  Mumbai   95.0  40000.000000
5  Pooja   22    MCA   Delhi   84.0  32000.000000
6  Arjun   24    MCA    Pune   81.0  32333.333333
7   Neha   23    MCA  Mumbai   79.0  29000.000000

In [ ]:
#syntax()

df.isnull()
df.isnull().sum()
df.fillna(value)
df.dropna()
df["column_name"].mean()

In [22]:
#-- Sorting :-- sorting mean arranging a data in ascending or descending 

#Sorting Step1: asending sort(defualt)

df.sort_values(by = "Marks")

#df(DataFrame),sort_values() -- sorting funcation ,by in which column you are sorting

    Name  Age Course    City  Marks        Salary
2  Rahul   22    MCA   Delhi   76.0  32333.333333
7   Neha   23    MCA  Mumbai   79.0  29000.000000
6  Arjun   24    MCA    Pune   81.0  32333.333333
1   Riya   24    MCA  Mumbai   84.0  35000.000000
5  Pooja   22    MCA   Delhi   84.0  32000.000000
0   Amit   23    MCA    Pune   85.0  30000.000000
3  Sneha   23    MCA    Pune   88.0  28000.000000
4  Karan   25    MCA  Mumbai   95.0  40000.000000

In [23]:
df.sort_values(by = "Marks",ascending = False)

    Name  Age Course    City  Marks        Salary
4  Karan   25    MCA  Mumbai   95.0  40000.000000
3  Sneha   23    MCA    Pune   88.0  28000.000000
0   Amit   23    MCA    Pune   85.0  30000.000000
1   Riya   24    MCA  Mumbai   84.0  35000.000000
5  Pooja   22    MCA   Delhi   84.0  32000.000000
6  Arjun   24    MCA    Pune   81.0  32333.333333
7   Neha   23    MCA  Mumbai   79.0  29000.000000
2  Rahul   22    MCA   Delhi   76.0  32333.333333

In [27]:
df.sort_values(by = ["Age","City"])

    Name  Age Course    City  Marks        Salary
2  Rahul   22    MCA   Delhi   76.0  32333.333333
5  Pooja   22    MCA   Delhi   84.0  32000.000000
7   Neha   23    MCA  Mumbai   79.0  29000.000000
0   Amit   23    MCA    Pune   85.0  30000.000000
3  Sneha   23    MCA    Pune   88.0  28000.000000
1   Riya   24    MCA  Mumbai   84.0  35000.000000
6  Arjun   24    MCA    Pune   81.0  32333.333333
4  Karan   25    MCA  Mumbai   95.0  40000.000000

In [25]:
df.sort_values(by = "Age",ascending = False)

    Name  Age Course    City  Marks        Salary
4  Karan   25    MCA  Mumbai   95.0  40000.000000
1   Riya   24    MCA  Mumbai   84.0  35000.000000
6  Arjun   24    MCA    Pune   81.0  32333.333333
0   Amit   23    MCA    Pune   85.0  30000.000000
7   Neha   23    MCA  Mumbai   79.0  29000.000000
3  Sneha   23    MCA    Pune   88.0  28000.000000
2  Rahul   22    MCA   Delhi   76.0  32333.333333
5  Pooja   22    MCA   Delhi   84.0  32000.000000

In [28]:
df.sort_values(by="Marks", ascending=False).head(3)

    Name  Age Course    City  Marks   Salary
4  Karan   25    MCA  Mumbai   95.0  40000.0
3  Sneha   23    MCA    Pune   88.0  28000.0
0   Amit   23    MCA    Pune   85.0  30000.0

In [29]:
df.sort_values(by="Marks", ascending=False).tail(3)

    Name  Age Course    City  Marks        Salary
6  Arjun   24    MCA    Pune   81.0  32333.333333
7   Neha   23    MCA  Mumbai   79.0  29000.000000
2  Rahul   22    MCA   Delhi   76.0  32333.333333

In [33]:
#basic analysis -- summarize the data to under stand it 

df.describe()

             Age    Marks        Salary
count   8.000000   8.0000      8.000000
mean   23.250000  84.0000  32333.333333
std     1.035098   5.8064   3804.758925
min    22.000000  76.0000  28000.000000
25%    22.750000  80.5000  29750.000000
50%    23.000000  84.0000  32166.666667
75%    24.000000  85.7500  33000.000000
max    25.000000  95.0000  40000.000000

In [34]:
df["Marks"].mean()

np.float64(84.0)

In [35]:
df["Marks"].max()

np.float64(95.0)

In [36]:
df["Marks"].min()

np.float64(76.0)

In [38]:
#Syntax revision 

df.sort_values

<bound method DataFrame.sort_values of     Name  Age Course    City  Marks        Salary
0   Amit   23    MCA    Pune   85.0  30000.000000
1   Riya   24    MCA  Mumbai   84.0  35000.000000
2  Rahul   22    MCA   Delhi   76.0  32333.333333
3  Sneha   23    MCA    Pune   88.0  28000.000000
4  Karan   25    MCA  Mumbai   95.0  40000.000000
5  Pooja   22    MCA   Delhi   84.0  32000.000000
6  Arjun   24    MCA    Pune   81.0  32333.333333
7   Neha   23    MCA  Mumbai   79.0  29000.000000>

In [42]:
df.columns

Index(['Name', 'Age', 'Course', 'City', 'Marks', 'Salary'], dtype='str')

In [43]:
df.sort_values(by="Marks")

    Name  Age Course    City  Marks        Salary
2  Rahul   22    MCA   Delhi   76.0  32333.333333
7   Neha   23    MCA  Mumbai   79.0  29000.000000
6  Arjun   24    MCA    Pune   81.0  32333.333333
1   Riya   24    MCA  Mumbai   84.0  35000.000000
5  Pooja   22    MCA   Delhi   84.0  32000.000000
0   Amit   23    MCA    Pune   85.0  30000.000000
3  Sneha   23    MCA    Pune   88.0  28000.000000
4  Karan   25    MCA  Mumbai   95.0  40000.000000

In [44]:
df.sort_values(by="Salary", ascending=False)

    Name  Age Course    City  Marks        Salary
4  Karan   25    MCA  Mumbai   95.0  40000.000000
1   Riya   24    MCA  Mumbai   84.0  35000.000000
6  Arjun   24    MCA    Pune   81.0  32333.333333
2  Rahul   22    MCA   Delhi   76.0  32333.333333
5  Pooja   22    MCA   Delhi   84.0  32000.000000
0   Amit   23    MCA    Pune   85.0  30000.000000
7   Neha   23    MCA  Mumbai   79.0  29000.000000
3  Sneha   23    MCA    Pune   88.0  28000.000000

In [45]:
df.sort_values(by="Marks")         # ✅ correct

    Name  Age Course    City  Marks        Salary
2  Rahul   22    MCA   Delhi   76.0  32333.333333
7   Neha   23    MCA  Mumbai   79.0  29000.000000
6  Arjun   24    MCA    Pune   81.0  32333.333333
1   Riya   24    MCA  Mumbai   84.0  35000.000000
5  Pooja   22    MCA   Delhi   84.0  32000.000000
0   Amit   23    MCA    Pune   85.0  30000.000000
3  Sneha   23    MCA    Pune   88.0  28000.000000
4  Karan   25    MCA  Mumbai   95.0  40000.000000

In [46]:
df.sort_values(by="Marks")  # ✅ (case-sensitive)

    Name  Age Course    City  Marks        Salary
2  Rahul   22    MCA   Delhi   76.0  32333.333333
7   Neha   23    MCA  Mumbai   79.0  29000.000000
6  Arjun   24    MCA    Pune   81.0  32333.333333
1   Riya   24    MCA  Mumbai   84.0  35000.000000
5  Pooja   22    MCA   Delhi   84.0  32000.000000
0   Amit   23    MCA    Pune   85.0  30000.000000
3  Sneha   23    MCA    Pune   88.0  28000.000000
4  Karan   25    MCA  Mumbai   95.0  40000.000000

In [48]:
df.columns = df.columns.str.strip()

In [49]:
df.head()
df.columns

Index(['Name', 'Age', 'Course', 'City', 'Marks', 'Salary'], dtype='str')

In [3]:
import pandas as pd

data = {
    "Name": ["Amit","Riya","Rahul","Sneha","Karan","Pooja","Arjun","Neha"],
    "City": ["Pune","Mumbai","Delhi","Pune","Mumbai","Delhi","Pune","Mumbai"],
    "Department": ["IT","HR","IT","Finance","HR","IT","Finance","HR"],
    "Salary": [50000,60000,55000,52000,58000,62000,51000,59000]
}

df = pd.DataFrame(data)
df

    Name    City Department  Salary
0   Amit    Pune         IT   50000
1   Riya  Mumbai         HR   60000
2  Rahul   Delhi         IT   55000
3  Sneha    Pune    Finance   52000
4  Karan  Mumbai         HR   58000
5  Pooja   Delhi         IT   62000
6  Arjun    Pune    Finance   51000
7   Neha  Mumbai         HR   59000

In [2]:
#groupby by is used to dividee data into group based on a column and then perform calculation

In [7]:
df.groupby("City")

In [9]:
df.groupby("City")["Salary"].mean()

City
Delhi     58500.0
Mumbai    59000.0
Pune      51000.0
Name: Salary, dtype: float64

In [10]:
df.groupby("City")["Name"].count()

City
Delhi     2
Mumbai    3
Pune      3
Name: Name, dtype: int64

In [12]:
df.groupby("City")["Salary"].max()

City
Delhi     62000
Mumbai    60000
Pune      52000
Name: Salary, dtype: int64

In [13]:
#multiple fun

In [16]:
#agg()  is used to apply multiple cal

df.groupby("City")["Salary"].agg(["sum", "min", "max", "count"])

           sum    min    max  count
City
Delhi   117000  55000  62000      2
Mumbai  177000  58000  60000      3
Pune    153000  50000  52000      3

In [30]:
df.groupby(["City","Department"])["Salary"].agg(["sum", "min", "max", "count","mean"])

                      sum    min    max  count     mean
City   Department
Delhi  IT          117000  55000  62000      2  58500.0
Mumbai HR          177000  58000  60000      3  59000.0
Pune   Finance     103000  51000  52000      2  51500.0
       IT           50000  50000  50000      1  50000.0

In [ ]:
#--- sentax
# df.groupby("column")
# df.groupby("column") ["column"].function()
# df.groupby("column") ["column"].agg(("function1", "function2"])
# df.groupby (["column1","column2"])["column"].function()

In [28]:
#qus which city has highest avg salary

df.groupby("City")["Salary"].mean().idxmax()

'Mumbai'

In [31]:
df.groupby("City")["Salary"].mean().nlargest(1)

City
Mumbai    59000.0
Name: Salary, dtype: float64

In [31]:
#merge by
import pandas as pd

data = {
    "Name": ["Amit", "Riya", "Karan"],
    "Salary": [30000, 35000, 40000]
}

df = pd.DataFrame(data)

# Now this will work


print(df)

    Name  Salary
0   Amit   30000
1   Riya   35000
2  Karan   40000

In [3]:
#pd.merge(df1,df2,on = "col",how = "type")


pd.merge(emp,salary)

   Emp_ID   Name  Salary
0     101   Amit   50000
1     102   Riya   60000
2     103  Rahul   55000

In [16]:
# Emp_ID	Name	Salary
# 0	101	    Amit	50000.0
# 1	102	    Riya	60000.0
# 2	103	   Rahul	55000.0
# 3	104	   Sneha	NaN
# 4	105	   NaN	     70000.0


#(inner join -- comman values show )
#(outer join -- all values show) 
#(left join -- left (NA)values not show,val show) 
#(Right join -- right (NA)values not show,val show) 




pd.merge(emp,salary,on = "Emp_ID",how = "outer")

   Emp_ID   Name   Salary
0     101   Amit  50000.0
1     102   Riya  60000.0
2     103  Rahul  55000.0
3     104  Sneha      NaN
4     105    NaN  70000.0

In [18]:
pd.concat([emp,salary])

   Emp_ID   Name   Salary
0     101   Amit      NaN
1     102   Riya      NaN
2     103  Rahul      NaN
3     104  Sneha      NaN
0     101    NaN  50000.0
1     102    NaN  60000.0
2     103    NaN  55000.0
3     105    NaN  70000.0

In [19]:
pd.concat([emp,salary],axis = 0)

   Emp_ID   Name   Salary
0     101   Amit      NaN
1     102   Riya      NaN
2     103  Rahul      NaN
3     104  Sneha      NaN
0     101    NaN  50000.0
1     102    NaN  60000.0
2     103    NaN  55000.0
3     105    NaN  70000.0

In [20]:
pd.concat([emp,salary],axis = 1)

   Emp_ID   Name  Emp_ID  Salary
0     101   Amit     101   50000
1     102   Riya     102   60000
2     103  Rahul     103   55000
3     104  Sneha     105   70000

In [21]:
#opeartion

In [32]:
df["bonus"] = df["Salary"] * 0.2

print(df)

    Name  Salary   bonus
0   Amit   30000  6000.0
1   Riya   35000  7000.0
2  Karan   40000  8000.0

In [44]:
import pandas as pd

emp = pd.DataFrame({
    "Emp_ID": [101,102,103,104],
    "Name": ["Amit","Riya","Rahul","Sneha"]
})

salary = pd.DataFrame({
    "Emp_ID": [101,102,103,105],
    "Salary": [50000,60000,55000,70000]
})

In [46]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
print(df)

    Name  Salary   bonus
0   Amit   30000  6000.0
1   Riya   35000  7000.0
2  Karan   40000  8000.0

In [ ]:
#1.Pivot tables: --- using a aggregation par
#pivot table is used to summarize data into a strucated table format

#df.pivot_table (values = "col",index = "col",aggfunc = "func")


#values -- calculate --- index,row,aggfunc

In [47]:
df

    Name  Salary   bonus
0   Amit   30000  6000.0
1   Riya   35000  7000.0
2  Karan   40000  8000.0

In [49]:
df.pivot_table(values="Salary", index="Emp_ID",colums = "Name", aggfunc="mean")

KeyError: 'Emp_ID'

In [50]:
df = pd.read_csv("firstcsv.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'firstcsv.csv'