In [2]:
#-- PANDAS --

In [4]:
!pip install pandas

Requirement already satisfied: pandas in e:\anaconda\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in e:\anaconda\lib\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in e:\anaconda\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in e:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
Real-Life Uses

✔ Easy data handling
✔ Fast and efficient
✔ Works with CSV, Excel, SQL
✔ Powerful data analysis tools
✔ Data Analysis
✔ Machine Learning
✔ Data Cleaning
✔ Business Reports

In [ ]:
What is Pandas?

- Pandas is a Python library used for data analysis & data manipulation
- Built on top of NumPy
- Works with structured data (tables)

In [5]:
#Import Pandas
import pandas as pd

In [7]:
import pandas as pd

print(pd.__version__)

3.0.0

In [ ]:
#1-- Pandas Series

What is a Series?
- A Pandas Series is like a column in a table.
- It is a one-dimensional array holding data of any type.

In [9]:
#1.


import numpy as np
import pandas as pd

In [22]:
#2

label = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
dic = {1:10,2:20,3:30}

In [17]:
#3

pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [23]:
#4

pd.Series(my_list,index = label)

a    10
b    20
c    30
dtype: int64

In [26]:
#5

pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [27]:
#6

pd.Series(dic)

1    10
2    20
3    30
dtype: int64

In [28]:
#2-- DataFrames --

In [52]:


import pandas as pd

In [31]:
#1.creating a data frames -- 


data = {
    'Name':['om','vish','ritu','petha'],
    'Age':[23,22,23,43],
    'City':['pune','solapur','nagpur','kolapur'],
    'Salary':[12000,30000,40000,50000]
}

In [33]:
data

{'Name': ['om', 'vish', 'ritu', 'petha'],
 'Age': [23, 22, 23, 43],
 'City': ['pune', 'solapur', 'nagpur', 'kolapur'],
 'Salary': [12000, 30000, 40000, 50000]}

In [41]:
df = pd.DataFrame(data)

In [42]:
df

    Name  Age     City  Salary
0     om   23     pune   12000
1   vish   22  solapur   30000
2   ritu   23   nagpur   40000
3  petha   43  kolapur   50000

In [44]:
data_list = {
    'Name':['om','vish','ritu','petha'],
    'Age':[23,22,23,43],
    'City':['pune','solapur','nagpur','kolapur'],
    'Salary':[12000,30000,40000,50000]
}

In [47]:
df2 = pd.DataFrame(data_list)

In [48]:
df2

    Name  Age     City  Salary
0     om   23     pune   12000
1   vish   22  solapur   30000
2   ritu   23   nagpur   40000
3  petha   43  kolapur   50000

In [49]:
columns = ['Name','Age','City','Salary']

In [57]:
df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age     City  Salary
0     om   23     pune   12000
1   vish   22  solapur   30000
2   ritu   23   nagpur   40000
3  petha   43  kolapur   50000

In [12]:
#2.Selecting and indexing of columns --

In [13]:

import pandas as pd

In [35]:
data_list = [
    ['om',23,'pune',12000],
    ['vish',22,'solapur',30000],
    ['ritu',33,'nagpur',40000],
    ['petha',43,'kolapur',50000]
]

columns = ['Name','Age','City','Salary']

df2 = pd.DataFrame(data_list, columns=columns)

In [15]:
df2["Name"]

0       om
1     vish
2     ritu
3    petha
Name: Name, dtype: str

In [16]:
df2 [["Name","Age"]]

    Name  Age
0     om   23
1   vish   22
2   ritu   23
3  petha   43

In [17]:
#3. Create new column

In [18]:
df2["Dep"] = ["Doc","Eng","tech","Doc"]

In [19]:
df2

    Name  Age     City  Salary   Dep
0     om   23     pune   12000   Doc
1   vish   22  solapur   30000   Eng
2   ritu   23   nagpur   40000  tech
3  petha   43  kolapur   50000   Doc

In [20]:
#4. Remove column --

In [21]:
#i. not delete data 

df2.drop("Dep",axis = 1)

    Name  Age     City  Salary
0     om   23     pune   12000
1   vish   22  solapur   30000
2   ritu   23   nagpur   40000
3  petha   43  kolapur   50000

In [22]:
df2

    Name  Age     City  Salary   Dep
0     om   23     pune   12000   Doc
1   vish   22  solapur   30000   Eng
2   ritu   23   nagpur   40000  tech
3  petha   43  kolapur   50000   Doc

In [23]:
#ii. parmanant data delete

df2.drop("Dep",axis = 1,inplace = True)

In [24]:
df2

    Name  Age     City  Salary
0     om   23     pune   12000
1   vish   22  solapur   30000
2   ritu   23   nagpur   40000
3  petha   43  kolapur   50000

In [26]:
#iii.  skip 0 (any column)--

df2.drop(0,axis = 0)

    Name  Age     City  Salary
1   vish   22  solapur   30000
2   ritu   23   nagpur   40000
3  petha   43  kolapur   50000

In [27]:
df2

    Name  Age     City  Salary
0     om   23     pune   12000
1   vish   22  solapur   30000
2   ritu   23   nagpur   40000
3  petha   43  kolapur   50000

In [30]:
#5. Selecting Row


#loc = location
#iloc = index location


df2.loc[0]

Name         om
Age          23
City       pune
Salary    12000
Name: 0, dtype: object

In [31]:
df2.loc[[0,1]]

   Name  Age     City  Salary
0    om   23     pune   12000
1  vish   22  solapur   30000

In [32]:
#6. seleting subset of Row and Columns -- 

df2.loc[[0,1]][["City","Salary"]]

      City  Salary
0     pune   12000
1  solapur   30000

In [33]:
#7. Conditional Serlection --

In [36]:
# i only want to see those people whose age is about 30

df2[df2["Age"] > 30]

    Name  Age     City  Salary
2   ritu   33   nagpur   40000
3  petha   43  kolapur   50000

In [43]:
# i only want people whose age is about 30 thire city must be kolapur

df2[(df2["Age"] > 30) & (df2["City"] == "kolapur")]

    Name  Age     City  Salary
3  petha   43  kolapur   50000

In [44]:
#3 -- Missing Data -- 
#i.Finding missing Data
#ii.Removing MD
#iii.filling MD

In [5]:
import numpy as np
import pandas as pd

In [6]:
#1.Finding missing Data

data = {
    'A':[1,2,np.nan,4,5],
    'B':[1,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}

df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [60]:
df.isnull()

#convert values (bool)

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [62]:
df.isnull().sum()

#count values

A    1
B    0
C    2
D    3
dtype: int64

In [64]:
df.isnull().any()

#extecting values

A     True
B    False
C     True
D     True
dtype: bool

In [8]:
#2.Removing missing data

df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [9]:
df.dropna()

#drop NaN remove Row

     A  B    C    D
0  1.0  1  1.0  1.0

In [12]:
df.dropna(thresh = 3) 

#drop non - NaN values remove Row

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [13]:
#3.Filling the missing data -- fillout using "0"

df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [14]:
values = {'A':0,'B':100,'C':300,'D':400}
df.fillna(value = values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [15]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [17]:
df.fillna(df.min())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  1.0
2  1.0  3  3.0  1.0
3  4.0  4  1.0  1.0
4  5.0  5  1.0  5.0

In [18]:
#4 -- Marging , joining , concationation

In [21]:
import numpy as np
import pandas as pd

#dataframes01
employees = pd.DataFrame({
    'Emp_id':[1,2,3,4,5],
    'Name':["vish","ritu","petha","om","og"],
    'Dep':["HR","IT","DOC","ENGG","TECH"]
    
})


#dataframes02
salaries = pd.DataFrame({
    'Emp_id':[1,2,3,4,5],
    'salary':[100000,200000,300000,400000,500000],
    'bonus':[10000,20000,30000,40000,50000]
    
})

In [22]:
employees

   Emp_id   Name   Dep
0       1   vish    HR
1       2   ritu    IT
2       3  petha   DOC
3       4     om  ENGG
4       5     og  TECH

In [23]:
salaries

   Emp_id  salary  bonus
0       1  100000  10000
1       2  200000  20000
2       3  300000  30000
3       4  400000  40000
4       5  500000  50000

In [25]:
#1.merging 2 dataframes 

pd.merge(employees,salaries)

#merging col

   Emp_id   Name   Dep  salary  bonus
0       1   vish    HR  100000  10000
1       2   ritu    IT  200000  20000
2       3  petha   DOC  300000  30000
3       4     om  ENGG  400000  40000
4       5     og  TECH  500000  50000

In [26]:
pd.merge(employees,salaries,on = "Emp_id",how = "inner")

   Emp_id   Name   Dep  salary  bonus
0       1   vish    HR  100000  10000
1       2   ritu    IT  200000  20000
2       3  petha   DOC  300000  30000
3       4     om  ENGG  400000  40000
4       5     og  TECH  500000  50000

In [27]:
pd.merge(employees,salaries,on = "Emp_id",how = "outer")

   Emp_id   Name   Dep  salary  bonus
0       1   vish    HR  100000  10000
1       2   ritu    IT  200000  20000
2       3  petha   DOC  300000  30000
3       4     om  ENGG  400000  40000
4       5     og  TECH  500000  50000

In [28]:
pd.merge(employees,salaries,on = "Emp_id",how = "right")

   Emp_id   Name   Dep  salary  bonus
0       1   vish    HR  100000  10000
1       2   ritu    IT  200000  20000
2       3  petha   DOC  300000  30000
3       4     om  ENGG  400000  40000
4       5     og  TECH  500000  50000

In [30]:
pd.merge(employees,salaries,on = "Emp_id",how = "left")

   Emp_id   Name   Dep  salary  bonus
0       1   vish    HR  100000  10000
1       2   ritu    IT  200000  20000
2       3  petha   DOC  300000  30000
3       4     om  ENGG  400000  40000
4       5     og  TECH  500000  50000

In [34]:
#2.Concationation of 2 dataframe : can is used to combine dataframes along row and columns 

df1 = pd.DataFrame({
    "A":["A0","A1","A2"],
    "B":["B0","B1","B2"],
    "C":["C0","C1","C2"]
})


df2 = pd.DataFrame({
    "A":["A3","A4","A5"],
    "B":["B3","B4","B5"],
    "C":["C3","C4","C5"]
})

In [32]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [35]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [36]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [37]:
pd.concat([df1,df2],axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [38]:
pd.concat([df1,df2],axis = 0)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [39]:
#3.joining of 2 dataframe

df1 = pd.DataFrame({
    "Name":["vish","ritu","om"]
},index = [1,2,3])



df2 = pd.DataFrame({
    "score":[95,75,46]
},index = [2,3,4])

In [40]:
df1

   Name
1  vish
2  ritu
3    om

In [41]:
df2

   score
2     95
3     75
4     46

In [42]:
df1.join(df2)

   Name  score
1  vish    NaN
2  ritu   95.0
3    om   75.0

In [43]:
df2.join(df1)

   score  Name
2     95  ritu
3     75    om
4     46   NaN

In [44]:
df1.join(df2,how = "outer")

   Name  score
1  vish    NaN
2  ritu   95.0
3    om   75.0
4   NaN   46.0

In [2]:
#5 -- GroupBy Aggregation -- 

import numpy as np
import pandas as pd

In [9]:
#1.groupbys 

import numpy as np
import pandas as pd

data = {
    'category': ["A","B","A","B","A","B","A","B"],
    'store': ["S1","S1","S2","S2","S1","S2","S1","S2"],
    'sale': [100,200,150,250,120,180,200,300],
    'quantity': [10,15,12,18,8,20,15,25],
    'date': pd.date_range("2023-01-01", periods=8)
}

df = pd.DataFrame(data)

print(df)

  category store  sale  quantity       date
0        A    S1   100        10 2023-01-01
1        B    S1   200        15 2023-01-02
2        A    S2   150        12 2023-01-03
3        B    S2   250        18 2023-01-04
4        A    S1   120         8 2023-01-05
5        B    S2   180        20 2023-01-06
6        A    S1   200        15 2023-01-07
7        B    S2   300        25 2023-01-08

In [ ]:
df

In [17]:
#qus -- groupby category and calculate the sum of sales 

cat = df.groupby("category")["sale"].sum()
cat

category
A    570
B    930
Name: sale, dtype: int64

In [18]:
#qus -- groupby store and calculate the sum of sales 

cat = df.groupby("store")["sale"].sum()
cat

store
S1    620
S2    880
Name: sale, dtype: int64

In [21]:
cat = df.groupby('category')      #imp

for i, v in cat:
    print(i)   # group name (A or B)
    print(v)   # group DataFrame

A
  category store  sale  quantity       date
0        A    S1   100        10 2023-01-01
2        A    S2   150        12 2023-01-03
4        A    S1   120         8 2023-01-05
6        A    S1   200        15 2023-01-07
B
  category store  sale  quantity       date
1        B    S1   200        15 2023-01-02
3        B    S2   250        18 2023-01-04
5        B    S2   180        20 2023-01-06
7        B    S2   300        25 2023-01-08

In [26]:
#groupby multiple columns
#groupby category and store

cat = df.groupby(["category","store"])["sale"].sum()
cat

category  store
A         S1       420
          S2       150
B         S1       200
          S2       730
Name: sale, dtype: int64

In [32]:
#2.Aggregation -- mutiple values convert - single mean values

#mean , median , min , max , count

df["sale"].agg(["sum", "min", "max", "count"])

sum      1500
min       100
max       300
count       8
Name: sale, dtype: int64

In [ ]:
#6 -- Pivot tables/Cross tab

In [10]:
#Dataframes:--

import pandas as pd
import numpy as np

# Corrected data dictionary
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South','East', 'West', 'North', 'South','East', 'West', 'North', 'South','East', 'West', 'North', 'South','East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice','John', 'Mary', 'Bob', 'Alice','John', 'Mary', 'Bob', 'Alice','John', 'Mary', 'Bob', 'Alice','John', 'Mary', 'Bob', 'Alice']
}

# Create the DataFrame
df = pd.DataFrame(data)


df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    964     13   John
1  2023-01-02       B   West    616     83   Mary
2  2023-01-03       C  North    704     24    Bob
3  2023-01-04       D  South    953     68  Alice
4  2023-01-05       A   East    858     67   John
5  2023-01-06       B   West    591     31   Mary
6  2023-01-07       C  North    784     15    Bob
7  2023-01-08       D  South    835     35  Alice
8  2023-01-09       A   East    626     75   John
9  2023-01-10       B   West    752     87   Mary
10 2023-01-11       C  North    257     17    Bob
11 2023-01-12       D  South    864     10  Alice
12 2023-01-13       A   East    524     32   John
13 2023-01-14       B   West    803     87   Mary
14 2023-01-15       C  North    390     95    Bob
15 2023-01-16       D  South    846     25  Alice
16 2023-01-17       A   East    680     51   John
17 2023-01-18       B   West    742     32   Mary
18 2023-01-19       C  North    423     74    Bob
19 2023-01-20       D  South    716     64  Alice

In [11]:
df["Month"] = df["Date"].dt.month_name()                      #--- add Month

In [19]:
df["Quarter"] = 'Q' + df["Date"].dt.quarter.astype(str)           #--- add Quarter values

In [20]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    964     13   John  January      Q1
1  2023-01-02       B   West    616     83   Mary  January      Q1
2  2023-01-03       C  North    704     24    Bob  January      Q1
3  2023-01-04       D  South    953     68  Alice  January      Q1
4  2023-01-05       A   East    858     67   John  January      Q1
5  2023-01-06       B   West    591     31   Mary  January      Q1
6  2023-01-07       C  North    784     15    Bob  January      Q1
7  2023-01-08       D  South    835     35  Alice  January      Q1
8  2023-01-09       A   East    626     75   John  January      Q1
9  2023-01-10       B   West    752     87   Mary  January      Q1
10 2023-01-11       C  North    257     17    Bob  January      Q1
11 2023-01-12       D  South    864     10  Alice  January      Q1
12 2023-01-13       A   East    524     32   John  January      Q1
13 2023-01-14       B   West    803     87   Mary  January      Q1
14 2023-01-15       C  North    390     95    Bob  January      Q1
15 2023-01-16       D  South    846     25  Alice  January      Q1
16 2023-01-17       A   East    680     51   John  January      Q1
17 2023-01-18       B   West    742     32   Mary  January      Q1
18 2023-01-19       C  North    423     74    Bob  January      Q1
19 2023-01-20       D  South    716     64  Alice  January      Q1

In [22]:
#1.Pivot tables: --- using a aggregation par
#pivot table is used to summarize data into a strucated table format

#df.pivot_table (values = "col",index = "col",aggfunc = "func")


#values -- calculate --- index,row,aggfunc

In [29]:
#creating pivot taable:--

pd.pivot_table(df,values = "Sales",index = "Region",columns = "Product")

Product      A      B      C      D
Region
East     730.4    NaN    NaN    NaN
North      NaN    NaN  511.6    NaN
South      NaN    NaN    NaN  842.8
West       NaN  700.8    NaN    NaN

In [33]:
#creating pivot taable:-- use aggrgation fun (to find median valus)

pd.pivot_table(df,values = "Sales",index = "Region",columns = "Product",aggfunc = "median")

Product      A      B      C      D
Region
East     680.0    NaN    NaN    NaN
North      NaN    NaN  423.0    NaN
South      NaN    NaN    NaN  846.0
West       NaN  742.0    NaN    NaN

In [41]:
pivot2 = pd.pivot_table(df,values = ["Sales","Units"],index = "Region",columns = "Product")
print(pivot2)

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     730.4    NaN    NaN    NaN  47.6   NaN   NaN   NaN
North      NaN    NaN  511.6    NaN   NaN   NaN  45.0   NaN
South      NaN    NaN    NaN  842.8   NaN   NaN   NaN  40.4
West       NaN  700.8    NaN    NaN   NaN  64.0   NaN   NaN

In [43]:
#2.cross tabs:-- using for counting per

In [45]:
pd.crosstab(df["Region"],df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0